version: '3.9'

services:
  app:
    build: .
    container_name: anki
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secret/key.json
    volumes:
      - ./src:/usr/src/app
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/secret/key.json